
client : 
    path : /
    controller: App\Controller\ClientController::index

liste_ues_par_diplomes : 
    path : /liste_ues_par_diplomes
    controller: App\Controller\ClientController::listeUesDiplomes

