
client : 
    path : /
    controller: App\Controller\ClientController::index

liste_ues_par_licence : 
    path : /liste_ues_par_licence
    controller: App\Controller\admin\DiplomesController::uesParLicence

