
dashboard : 
    path : /dashboard
    controller: App\Controller\admin\DashboardController::dashboard

login :
    path: /
    controller: App\Controller\admin\DashboardController::login

register :
    path : /register
    controller: App\Controller\admin\DashboardController::register

utilisateur :
    path : /utilisateur
    controller : App\Controller\admin\DashboardController::utilisateur

diplome :
    path : /diplome
    controller : App\Controller\admin\DiplomesController::afficher

ajout_diplome:
    path : /ajout_diplome
    controller : App\Controller\admin\DiplomesController::ajouter

modifier_diplome:
    path : /modifier_diplome-{id}
    controller : App\Controller\admin\DiplomesController::modifier
    requirements :
        id : '\d+'

supprimer_diplome:
    path : /supprimer_diplome-{id}
    controller : App\Controller\admin\DiplomesController::supprimer
    requirements :
        id : '\d+'

parcours :
    path : /parcours
    controller : App\Controller\admin\ParcoursController::afficher

ajouter_parcours :
    path : /ajouter_parcours
    controller : App\Controller\admin\ParcoursController::ajouter

modifier_parcours :
    path : /modifier_parcours-{id}
    controller : App\Controller\admin\ParcoursController::modifier
    requirements :
        id : '\d+'

supprimer_parcours :
    path : /supprimer_parcours-{id}
    controller : App\Controller\admin\ParcoursController::supprimer
    requirements :
        id : '\d+'

blocs_connaissances :
    path : /blocs_connaissances
    controller : App\Controller\admin\BlocsConnaissancesController::afficher

ajouter_blocs_connaissances :
    path : /ajouter_blocs_connaissances
    controller : App\Controller\admin\BlocsConnaissancesController::ajouter

modifier_blocs_connaissances :
    path : /modifier_blocs_connaissances-{id}
    controller : App\Controller\admin\BlocsConnaissancesController::modifier
    requirements :
        id : '\d+'

supprimer_blocs_connaissances :
    path : /supprimer_blocs_connaissances-{id}
    controller : App\Controller\admin\BlocsConnaissancesController::supprimer
    requirements :
        id : '\d+'


blocs_competences :
    path : /blocs_competences
    controller : App\Controller\admin\BlocsCompetencesController::afficher

ajouter_blocs_competences :
    path : /ajouter_blocs_competences
    controller : App\Controller\admin\BlocsCompetencesController::ajouter

modifier_blocs_competences :
    path : /modifier_blocs_competences-{id}
    controller : App\Controller\admin\BlocsCompetencesController::modifier
    requirements :
        id : '\d+'

supprimer_blocs_competences :
    path : /supprimer_blocs_competences-{id}
    controller : App\Controller\admin\BlocsCompetencesController::supprimer
    requirements :
        id : '\d+'


competence :
    path : /competence
    controller : App\Controller\admin\CompetencesController::afficher

ajouter_competence :
    path : /ajouter_competence
    controller : App\Controller\admin\CompetencesController::ajouter

modifier_competence :
    path : /modifier_competence-{id}
    controller : App\Controller\admin\CompetencesController::modifier
    requirements :
        id : '\d+'

supprimer_competence :
    path : /supprimer_competence-{id}
    controller : App\Controller\admin\CompetencesController::supprimer
    requirements :
        id : '\d+'

connaissance :
    path : /connaissance
    controller : App\Controller\admin\ConnaissancesController::afficher

ajouter_connaissance :
    path : /ajouter_connaissance
    controller : App\Controller\admin\ConnaissancesController::ajouter

modifier_connaissance :
    path : /modifier_connaissance
    controller : App\Controller\admin\ConnaissancesController::modifier

supprimer_connaissance :
    path : /supprimer_connaissance
    controller : App\Controller\admin\ConnaissancesController::supprimer


ues :
    path : /ues
    controller : App\Controller\admin\UesController::afficher

ajouter_ues :
    path : /ajouter_ues
    controller : App\Controller\admin\UesController::ajouter

modifier_ues :
    path : /modifier_ues-{id}
    controller : App\Controller\admin\UesController::modifier
    requirements :
        id : '\d+'

supprimer_ues :
    path : /supprimer_ues-{id}
    controller : App\Controller\admin\UesController::supprimer
    requirements :
        id : '\d+'

mcc :
    path : /mcc
    controller : App\Controller\admin\MccController::afficher

ajouter_mcc :
    path : /modifier_mcc
    controller : App\Controller\admin\MccController::ajouter

modifier_mcc :
    path : /modifier_mcc
    controller : App\Controller\admin\MccController::modifier

supprimer_mcc :
    path : /supprimer_mcc
    controller : App\Controller\admin\MccController::supprimer


